#!/bin/bash -e

echo "updating series..."
cd series
geo-series-update.sh 
Rscript process-series.R
cd ../

echo "updating platforms..."
cd platform
geo-platform-update.sh 
Rscript process-platforms.R
cd ../

echo "copying new RData files to shinyGEO"

cp series/series.RData ../shinyGEO/series/
cp platform/platforms.RData ../shinyGEO/platforms/

echo "update complete"

